import { formatCurrency } from './format'

export interface PrintItem {
  name: string
  qty: number
  price: number
  total: number
}

export interface PrintData {
  invoiceNumber: string
  invoiceDate: string
  items: PrintItem[]
  grandTotal: number
  notes?: string | null
  companyName: string
  address: string
  phone: string
  logo: string
  language: string
}

export function buildPrintHtml(data: PrintData): string {
  const dir = data.language === 'ar' ? 'rtl' : 'ltr'

  const logoHtml = data.logo
    ? `<img src="${data.logo}" alt="" />`
    : ''

  const lineHtml = data.items
    .map(
      (item, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${item.name}</td>
        <td>${item.qty}</td>
        <td>${formatCurrency(item.price)}</td>
        <td>${formatCurrency(item.total)}</td>
      </tr>`
    )
    .join('')

  const notesHtml = data.notes
    ? `<div class="notes"><strong>Notes:</strong> ${data.notes}</div>`
    : ''

  return `<!DOCTYPE html>
<html dir="${dir}">
<head>
<meta charset="utf-8">
<title>Invoice #${data.invoiceNumber}</title>
<style>
  @page { size: A4; margin: 10mm; }
  * { box-sizing: border-box; }
  body { font-family: Arial, sans-serif; font-size: 10pt; line-height: 1.4; margin: 0; padding: 0; color: #222; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #333; }
  .header-left h1 { font-size: 18pt; margin: 0 0 2px 0; font-weight: 700; letter-spacing: 0.5px; }
  .header-left .meta { font-size: 10pt; color: #555; margin: 1px 0; }
  .header-right { text-align: right; font-size: 10pt; line-height: 1.5; }
  .header-right img { max-height: 55px; max-width: 150px; margin-bottom: 4px; display: block; float: right; }
  .header-right .cname { font-weight: 700; font-size: 11pt; }
  html[dir="rtl"] .header-right { text-align: left; }
  html[dir="rtl"] .header-right img { float: left; }
  html[dir="rtl"] .header { flex-direction: row-reverse; }
  table { width: 100%; border-collapse: collapse; }
  thead { display: table-header-group; }
  th { background: #f0f0f0; font-weight: 600; font-size: 9pt; padding: 7px 8px; border: 1px solid #bbb; text-align: left; text-transform: uppercase; letter-spacing: 0.3px; }
  td { padding: 6px 8px; border: 1px solid #ddd; font-size: 10pt; text-align: left; vertical-align: top; }
  td:nth-child(1) { width: 36px; text-align: center; vertical-align: middle; }
  td:nth-child(3) { text-align: center; vertical-align: middle; }
  td:nth-child(4) { text-align: right; vertical-align: middle; }
  td:nth-child(5) { text-align: right; font-weight: 600; vertical-align: middle; }
  th:nth-child(1) { width: 36px; text-align: center; }
  th:nth-child(3) { text-align: center; }
  th:nth-child(4) { text-align: right; }
  th:nth-child(5) { text-align: right; }
  tbody tr { page-break-inside: avoid; }
  .totals { margin-left: auto; width: 320px; border-top: 2px solid #333; padding-top: 8px; margin-top: 16px; }
  .totals .grand { display: flex; justify-content: space-between; font-size: 14pt; font-weight: 700; padding: 6px 0; letter-spacing: 0.3px; }
  .notes { margin-top: 16px; font-size: 10pt; color: #555; padding: 8px 10px; border: 1px solid #eee; background: #fafafa; }
  .footer { text-align: center; font-size: 9pt; color: #999; margin-top: 24px; padding-top: 8px; border-top: 1px solid #eee; }
</style>
</head>
<body>
  <div class="header">
    <div class="header-left">
      <h1>INVOICE #${data.invoiceNumber}</h1>
      <div class="meta">Date: ${data.invoiceDate}</div>
    </div>
    <div class="header-right">
      ${logoHtml}
      <div class="cname">${data.companyName}</div>
      ${data.address ? data.address + '<br/>' : ''}${data.phone ? data.phone : ''}
    </div>
  </div>

  <table>
    <thead>
      <tr><th>#</th><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr>
    </thead>
    <tbody>
      ${lineHtml}
    </tbody>
  </table>

  <div class="totals">
    <div class="grand"><span>Grand Total</span><span>${formatCurrency(data.grandTotal)}</span></div>
  </div>
  ${notesHtml}

  <div class="footer">Thank you for your business.<br/><span style="color:#bbb;font-size:9px">Generated by Fatoora Pro &mdash; Developed by Elbara Mouaffak</span></div>
</body>
</html>`
}
